# Generated by Django 4.1.2 on 2023-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gallery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
