# Generated by Django 4.1.2 on 2023-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_gallery_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(default="", max_length=1000),
        ),
    ]
